### ISSUE TITLE
Problem starting server

### ISSUE THREAD

**Issue by ghost** [wellyshen/react-cool-starter#112]
Keep getting this error on `yarn start` and `yarn start:prod`
```
index.js:20
).server(dirRoot, () => {
^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by ghost** [comment]
You must change it to
```
global.webpackIsomorphicTools = new WebpackIsomorphicTools(require('./tools/webpack/WIT.config'))
  .server(dirRoot, () => {
    require('./src/server');
  });
```

**Comment by ghost** [comment]
Also `devtools` flag shouldn't be used in production as per the Webpack devtools docs
Change to `devtool: isDev ? 'cheap-module-eval-source-map' : '',` inside `config.babel`
