### ISSUE TITLE
TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by rtagithub** [wellyshen/react-cool-starter#241]
Thank you for the boilerplate that is very helpful for me.
The problem I  faced with is  the cooler stater compatibility with ant.design that is our hand to develop react SSR web application.
Additionally we need to do some test with jest and enzyme on the component but I faced with the following problem:

 FAIL  src/components/Sidebar/Sidebar.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'add' of undefined

With it’s stack trace : 

      at Object.add (node_modules/antd/lib/icon/icon/index.jsx:23:11)
      at Object.<anonymous> (node_modules/antd/lib/layout/layout/Sider.jsx:19:1)
      at Object.<anonymous> (node_modules/antd/lib/layout/layout/index.jsx:2:1)
      at Object.<anonymous> (src/components/App/AuthorizedWrapper.js:160:38)
      at Object.<anonymous> (src/components/App/index.js:1:1)
      at Object.<anonymous> (src/components/index.js:4:1)
      at Object.<anonymous> (src/components/Sidebar/Sidebar.test.js:3:1)

I was wondering if you would mind me helping with the issue.

**Comment by wellyshen** [comment]
@rtagithub This is the issue between `ant` and `jest`. Have you found the solution?

**Comment by rtagithub** [comment]
yes we done it here https://github.com/parham-fazlali/react-panda

**Comment by wellyshen** [comment]
@rtagithub I just see a panda on README bro...
