### ISSUE TITLE
Error when running server.js

### ISSUE THREAD

**Issue by xakep139** [wellyshen/react-cool-starter#37]
After successfull `yarn install` and `yarn build`, command `node ./build/server.js` return error:

```
C:\Users\n.balabaev\Source\Repos\react-cool-starter>node ./build/server.js
C:\Users\n.balabaev\Source\Repos\react-cool-starter\build\server.js:468
if (__DEV__) {
    ^

ReferenceError: __DEV__ is not defined
    at Object.<anonymous> (C:\Users\n.balabaev\Source\Repos\react-cool-starter\build\server.js:468:5)
    at __webpack_require__ (C:\Users\n.balabaev\Source\Repos\react-cool-starter\build\server.js:21:30)
    at Object.<anonymous> (C:\Users\n.balabaev\Source\Repos\react-cool-starter\build\server.js:1761:18)
    at __webpack_require__ (C:\Users\n.balabaev\Source\Repos\react-cool-starter\build\server.js:21:30)
    at C:\Users\n.balabaev\Source\Repos\react-cool-starter\build\server.js:67:18
    at Object.<anonymous> (C:\Users\n.balabaev\Source\Repos\react-cool-starter\build\server.js:70:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by xakep139** [comment]
If `index.js` is start point to launch server, `webpack-isomorphic-tools` should be moved to dependencies from devDependencies in `package.json`

**Comment by wellyshen** [comment]
Hi @xakep139 The entry point of `index.js` includes global variables and settings of webpack-isomorphic-tools, therefore the right command will be `node index.js` after building.

BTW, thank you for your recommend I have refined it :)
